### ISSUE TITLE
What is getOxygenSaturationSamples read Permission?

### ISSUE THREAD

**Issue by denisvely** [agencyenterprise/react-native-health#100]
Guys i want to get OxygenSaturationSamples but i get 
"error getting oxygen saturation:Error Domain=com.apple.healthkit Code=5 "Authorization not determined" UserInfo={NSLocalizedDescription=Authorization not determined}".

Could someone tell me which permission should i request to get Oxygen Saturation data?

**Comment by fakeheal** [comment]
Hello,
based on Apple's HealthKit documentation you need: [`HKQuantityTypeIdentifierOxygenSaturation`](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifieroxygensaturation?language=objc), which is exposed in [`Permissions`](https://github.com/agencyenterprise/react-native-health/blob/v2/RCTAppleHealthKit/RCTAppleHealthKit%2BTypesAndPermissions.m#L169) through [`RCTAppleHealthKit+TypesAndPermissions.m`](https://github.com/agencyenterprise/react-native-health/blob/v2/RCTAppleHealthKit/RCTAppleHealthKit%2BTypesAndPermissions.m#L169).

So your permissions array that you pass to `initHealthKit`, needs to include: `AppleHealthKit.Constants.Permissions. OxygenSaturation`.

If you're having any troubles with this setup, please post your code.

**Comment by denisvely** [comment]
@fakeheal Thank You!

**Comment by kp72-dev** [comment]
Facing same issue:
is there any configuration to do with info plist or somewhere else??

response I got is:

- [ ]  **AppleHealthKit.getSamples:::{"message":"error getting samples:Error Domain=com.apple.healthkit Code=5 \"Authorization not determined\" UserInfo={NSLocalizedDescription=Authorization not determined}"}**



`let storedLastDate = await getLastDate();
    let currentDate =
      moment(storedLastDate).format('YYYY-MM-DDTHH:MM:00.000') + 'Z';
    let options = {
      startDate: new Date(currentDate).toISOString(),
      endDate: new Date().toISOString(),
      type: ['Walking', 'Running'],
    };
    let permissions = {
      permissions: {
        read: [
          AppleHealthKit.Constants.Permissions.StepCount,
          AppleHealthKit.Constants.Permissions.Steps,
          AppleHealthKit.Constants.Permissions.ActiveEnergyBurned,
        ],
        write: [
          AppleHealthKit.Constants.Permissions.StepCount,
          AppleHealthKit.Constants.Permissions.Steps,
          AppleHealthKit.Constants.Permissions.ActiveEnergyBurned,
        ],
      },
    };
    await AppleHealthKit.initHealthKit(permissions, async (err, response) => {
      console.log(err);
      console.log('response init kit observer::' + JSON.stringify(response));
      if (response == 1) {
        AppleHealthKit.getAuthStatus(permissions, (err, res) => {
          if (
            res.permissions.read == [2, 2] &&
            res.permissions.write == [2, 2]
          ) {
            AppleHealthKit.getSamples(options, (err, results) => {
              if (err) {
                console.log(
                  'AppleHealthKit.getSamples error:::' + JSON.stringify(err),
                );
                return;
              }
              console.log('Retrving steps live:::' + JSON.stringify(results));
            });
          }
        });
      }
    });`

@macelai

**Comment by macelai** [comment]
hey @kp72-dev, check https://github.com/agencyenterprise/react-native-health/blob/master/docs/permissions.md

Maybe, `DistanceWalkingRunning` and `DistanceWalkingRunning `
