### ISSUE TITLE
Total Fat samples?

### ISSUE THREAD

**Issue by bvelasquez** [agencyenterprise/react-native-health#107]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I've noticed that permission to get total fat is available, but there is no getter for this. Is there a way to get the total fat consumed (dietary). Carbohydrates and Proteins are currently available.

A getTotalFatSamples().

**Describe alternatives you've considered**

**Additional context**

**Comment by bvelasquez** [comment]
Actually, there is a saveFood() in RCTAppleHealthKit+Methods_Dietary.m, maybe a getFood() is better than a getTotalFatSamples(), so we can get all the food entries.

**Comment by alesso-x** [comment]
@bvelasquez is implementing `getFood` method possible? I was going to take a look at your `getTotalFatSamples` and try to replicate for `getFood`.

**Comment by RuanAzevedo** [comment]
I am closing this issue since the PR is already merged.

**Comment by RuanAzevedo** [comment]
I am closing this issue since the PR is already merged.
