### ISSUE TITLE
HKElectrocardiogram

### ISSUE THREAD

**Issue by khwalkowicz** [agencyenterprise/react-native-health#112]
Hi! :wave:
Is there any chance the support for [KHElectrocardiogram](https://developer.apple.com/documentation/healthkit/hkelectrocardiogram) would come anytime soon?

**Comment by klandell** [comment]
@khwalkowicz I need this feature too.  I'll try to create a PR for this in the next few days.

**Comment by klandell** [comment]
I started looking at this. The logic seems like it will be fairly similar to #130, so I would like to wait until that PR is reviewed before implementing this one. Once started, this task shouldn't take very long to complete.
