### ISSUE TITLE
Support querying activity goals (move, exercise, stand)

### ISSUE THREAD

**Issue by KyleRosenberg** [agencyenterprise/react-native-health#118]
**Is your feature request related to a problem? Please describe.**
Accessing these goals is an essential part of our app

**Describe the solution you'd like**
We can call a function or functions to retrieve these values

**Describe alternatives you've considered**
Have our users manually set their goals separately in our app

**Comment by KyleRosenberg** [comment]
I've started working on this here https://github.com/KyleRosenberg/react-native-health/tree/activity-summary

**Comment by GGGava** [comment]
Thank you very much @KyleRosenberg, we will be waiting for your PR, let us know if you face any issue 😄
