### ISSUE TITLE
[Filter Manual enter data] Step

### ISSUE THREAD

**Issue by batical** [agencyenterprise/react-native-health#12]
**Is your feature request related to a problem? Please describe.**
I would like to filter the manual added data. For exemple get the number of step without manual added data

**Describe the solution you'd like**
in the options, add a flag to include manual or not

**Comment by lucaspbordignon** [comment]
Hey @batical! Thanks for the suggestion, that's a really valuable addition to the repository. I've also seen that we have the same request added to the original repository but was never really merged to master

We can definitively base our solution on that. The resources are the following

- https://github.com/terrillo/rn-apple-healthkit/issues/28
- https://github.com/terrillo/rn-apple-healthkit/pull/74

**Comment by batical** [comment]
you already did it. thanks

**Comment by lucaspbordignon** [comment]
@batical Yeah! I actually noticed that we already have the `includeManuallyAdded` flag for the `getDailyStepCountSamples` method, but we can probably filter all the other metrics too based on that flag

Also, feel free to go ahead and create a draft PR in case you need that functionality as soon as possible. I probably won't be able to work on it in the next few days, but can help complete the remaining methods in about a week from now (if any remaining method need to be updated)

**Comment by batical** [comment]
I can maybe try to copy from the other PR but I have no real knowledge of ObjC or Swift

**Comment by lucaspbordignon** [comment]
@batical We do have some great references added in PR #24 too, in case it helps
