### ISSUE TITLE
Native event callbacks not firing

### ISSUE THREAD

**Issue by moulie415** [agencyenterprise/react-native-health#140]
I've gone through the process of adding the setup code to the AppDelegate but nothing seems to work
```
 NativeAppEventEmitter.addListener('healthKit:Workout:setup:failure', () =>
      console.log('setup failed'),
 );

NativeAppEventEmitter.addListener('healthKit:Workout:setup:success', () =>
     console.log('setup success'),
);
```

I don't get any logs in the console.

- Device: iPhone5s
- OS: iOS 12.5.4

**Comment by macelai** [comment]
Hey @moulie415, please give another try on that, we updated some code related to listeners.
