### ISSUE TITLE
getWeightSample typescript error

### ISSUE THREAD

**Issue by dancixx** [agencyenterprise/react-native-health#141]
**Describe the bug**
The `getWeightSamples` methods `options` object has typescript error. `startDate` is not assignable to parameter of type 'HealthUnitOptions'.

**To Reproduce**

```
AppleHealthKit.getWeightSamples(
                    {
                        startDate: new Date(startDate).toISOString(), // required
                        endDate: new Date(endDate).toISOString(), // optional; default now
                    },

```

**Screenshots**
![Képernyőfotó 2021-08-03 - 0 23 30](https://user-images.githubusercontent.com/56868953/127931195-f5249cfb-f809-42a7-9f13-7c01afd122eb.png)

**Comment by macelai** [comment]
Hey @dancixx, want to open a PR for that? this a easy fix, just change the interface on `index.d.ts`
