### ISSUE TITLE
Unknown background delivery frequency, possibly not working at all

### ISSUE THREAD

**Issue by garymillergit** [agencyenterprise/react-native-health#144]
**Describe the bug**
I am unsure if my app is receiving updates from Apple health kit in the background. I've followed all the steps of installing `react-native-health` & the background observables. I know my setup worked because I can see the following in the XCode logs.
```
[HealthKit] Background observers will be added to the app
[HealthKit] Background observers added to the app
[HealthKit] New sample received from Apple HealthKit - StepCount
[HealthKit] New sample from Apple HealthKit processed - StepCount
```
when I build my app I also see `Setup Successful` in my logs from the following code.

_code snippet A_
```javascript
NativeAppEventEmitter.addListener('healthKit:StepCount:setup:success', () =>
  console.log('Setup Successful'),
);
NativeAppEventEmitter.addListener('healthKit:StepCount:new', () => {
  console.log('New');
});
```
I can only get `New` to print if I open and close the app. If I repeatedly close and open the app, after about 3-5 times `New` will be printed in the logs.

I know these listeners are being set but I don't know if they are ever firing in the background.

**To Reproduce**
N/A

**Expected behavior**
What is the expected background delivery rate? [This frequency param](https://developer.apple.com/documentation/healthkit/hkhealthstore/1614175-enablebackgrounddelivery) makes me believe it can be realtime or at least close to realtime. I'm hoping [this article](https://stackoverflow.com/questions/26375767/healthkit-background-delivery-when-app-is-not-running) is out of date (6 years old). Regardless, it doesn't seem like its updating in the background at all.

**Screenshots**
N/A

**Smartphone (please complete the following information):**

- Device: iPhone12
- OS: iOS14.4
- Version: react-native-health (1.10) (latest)

**Additional context**
I've put _code snippet A_ in `index.js`, `app.js` (in useEffect) and in my main navigator (in useEffect). All 3 places produce the same results.

**Questions**

- Where is the best place to put _code snippet A_?
- If close to realtime background delivery isn't possible with `react-native-health`, is it because Apple doesn't provide that feature or is it a limitation of `react-native-health`.
- What is the best way to debug/troubleshoot background delivery? I know I can manually add step data to Apple Health Kit but this doesn't fire an event unless I repeatedly open the app.

I know there are similar issues open but I'm not sure they are exactly like my situation. I wanted to provide my exact scenario.

Thanks in advance for any help. I tried to debug this for awhile because I do not what to waste your time but I cannot figure it out. My app is extremely dependent on this data being updated in the background.

**Comment by macelai** [comment]
There were some changes related to background processing, please update with master and give a try.
