### ISSUE TITLE
How can i save clinical documents?

### ISSUE THREAD

**Issue by caglardurmus** [agencyenterprise/react-native-health#145]
I want to save some clinical documents to user health. 
How can i do that? I saw the get method but i didn't see save method.

**Comment by macelai** [comment]
Hey @caglardurmus, we don't have that feature yet. Feel free to open a PR for that

**Comment by caglardurmus** [comment]
I see, are you considering adding such a feature soon?

**Comment by macelai** [comment]
I don't think anyone is working on that right now. Most of the new features come from the community

**Comment by klandell** [comment]
@caglardurmus The clinical records are read-only properties in Apple Health.  See Apple's article here: https://developer.apple.com/documentation/healthkit/samples/accessing_health_records
