### ISSUE TITLE
How can I delete all steps?

### ISSUE THREAD

**Issue by Dubask** [agencyenterprise/react-native-health#146]
Im listening to user steps, and every time he enters the app, Im saving the steps in the DB, and then i want to init them to 0.

How can I do that?

Thank you!

**Comment by macelai** [comment]
Hey @Dubask, you can't delete steps from the library, not sure if I understood your case. But looks like you would have to do a way to know when you "processed" that information already, is that so?

**Comment by Dubask** [comment]
Yes.
I want to know which steps are already processed, so I can add only the new steps.
Maybe there is on option to add hours?

**Comment by macelai** [comment]
If you are using the background listener, I don't think so. But if you are using something like [getSamplse](https://github.com/agencyenterprise/react-native-health/blob/master/docs/getSamples.md) you can specify the date.
