### ISSUE TITLE
getStepCount startDate not working

### ISSUE THREAD

**Issue by annabelschmitz12** [agencyenterprise/react-native-health#155]
If I set startDate in the options, I still only get the result from today.

For e.g. i have in Health for 2021-09-06 24 Steps and for 2021-09-07 73 Steps so if i set the startDate in options to `new Date('2021-09-06').toISOString()`
i still get this result:
`{"endDate": "2021-09-07T11:42:58.470+0200", "startDate": "2021-09-07T11:32:57.878+0200", "value": 73}`

**Comment by macelai** [comment]
Hey, actually the implementation for getStepCount is for one day, you can only pass a date, that will be the day for the step count. See `fitness_getStepCountOnDay`

**Comment by AlbertoMeQ** [comment]
Any way to get this to return a list of steps for each date in the range?

**Comment by evanjmg** [comment]
passing the day does not work for me as described. I get 0 steps even when manually added is true. I have 12000 added for the day I send -> new Date().toISOString()

**Comment by evanjmg** [comment]
I resolved this issue by adding the read permission to permissions AppleHealthKit.Constants.Permissions.Steps and using getDailyStepCountSamples. @macelai  you should close this issue
