### ISSUE TITLE
Possibility to save Heart Rates?

### ISSUE THREAD

**Issue by AlbertoMeQ** [agencyenterprise/react-native-health#162]
I cannot find a way to store Heart Rates with this library, just to retrieve them.

I would like to have something like:

```
let options = {
  value: 75, // BPM
  date: Date.now().toISOString()
}

AppleHealthKit.saveHeartRateSample(
  (options: HealthInputOptions),
  (err: Object, result: number) => {
    if (err) {
      console.log('error saving heart rate to Healthkit: ', err)
      return
    }
    // heart rate successfully saved
  },
)
```

Here is an idea on the possible implementation: https://stackoverflow.com/a/27268690/1214469 for Swift.

**Comment by macelai** [comment]
hey @AlbertoMeQ, thanks for collaborating with the project. Feel free to open an PR for that.

**Comment by Nesh108** [comment]
I also found this useful, so I made a PR about it!
