### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: healthKit:ActiveEnergyBurned:setup:success with body: { }. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in RCTAppleHealthKit, even though it's inherited from RCTEventEmitter.'

### ISSUE THREAD

**Issue by shaheem-khanzada** [agencyenterprise/react-native-health#166]
2021-10-14 15:40:31.225818+0500 nikenft[2680:1606672] [HealthKit] Background observers will be added to the app
2021-10-14 15:40:31.228034+0500 nikenft[2680:1606672] [HealthKit] Background observers added to the app
2021-10-14 15:40:31.233119+0500 nikenft[2680:1606919] *** Assertion failure in -[RCTEventEmitter sendEventWithName:body:](), /Users/muhammadshaheem/Documents/Work/Projects/nikenft/node_modules/react-native/React/Modules/RCTEventEmitter.m:58
2021-10-14 15:40:31.233242+0500 nikenft[2680:1606918] [connection] nw_endpoint_handler_set_adaptive_read_handler [C2 172.20.10.2:8081 ready socket-flow (satisfied (Path is satisfied), viable, interface: bridge100, ipv4, dns)] unregister notification for read_timeout failed
2021-10-14 15:40:31.233335+0500 nikenft[2680:1606918] [connection] nw_endpoint_handler_set_adaptive_write_handler [C2 172.20.10.2:8081 ready socket-flow (satisfied (Path is satisfied), viable, interface: bridge100, ipv4, dns)] unregister notification for write_timeout failed
2021-10-14 15:40:31.234060+0500 nikenft[2680:1606919] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: healthKit:ActiveEnergyBurned:setup:success with body: {
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in RCTAppleHealthKit, even though it's inherited from RCTEventEmitter.'
*** First throw call stack:
(0x1883f6708 0x19cf007a8 0x1882f83b8 0x18972181c 0x104dc1894 0x104c43374 0x10932c0b4 0x10932dde0 0x109335ef0 0x109336d48 0x109343a50 0x1d40667a4 0x1d406d74c)
libc++abi: terminating with uncaught exception of type NSException
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: healthKit:ActiveEnergyBurned:setup:success with body: {
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in RCTAppleHealthKit, even though it's inherited from RCTEventEmitter.'

![image](https://user-images.githubusercontent.com/37620819/137302912-838f521c-9b73-4513-a994-2463f55cf160.png)

I am getting these issues when adding Background Observer Support 

```
#import "AppDelegate.h"

...

/* Add the library import at the top of AppDelegate.m */
#import "RCTAppleHealthKit.h"

...

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self
                                            launchOptions:launchOptions];

  ...

  /* Add Background initializer for HealthKit  */
  [[RCTAppleHealthKit new] initializeBackgroundObservers:bridge];

  ...

  return YES;
}
```

**Comment by shaheem-khanzada** [comment]
@moulie415 thanks 🙏

**Comment by mnakai** [comment]
Probably facing the same issue.

my environments.
Xcode 13.1
iOS 14.8.1  (iPhone 6s)
RN 0.66.3
react-native-health 1.12.0, 1.11.0, 1.10.0

The app will close immediately after launching.

Exception NSException * "Error when sending event: healthKit:ActiveEnergyBurned:setup:success with body: {\n}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in RCTAppleHealthKit, even though it's inherited from RCTEventEmitter." 0x0000000281bc1a10

Does anyone have "Background Observers" working?

**Comment by mnakai** [comment]
> @moulie415 thanks 🙏

Did it work after downgrading?

Im facing the same issue on v1.10.0,v1.11.0,v1.12.0.

**Comment by camposer** [comment]
@moulie415 downgrading to 1.10.0 works. But when you try to get samples in the background listener, it always obtains empty. The console logs multiple times: "RNHealth: An error occured while trying to add sample from: com.apple.health.<bundle-id>" (similar to #177)

Any ideas? 

My App.tx:
```
import React, {useState} from 'react';
import {
  NativeAppEventEmitter,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';

import {
  Colors,
  Header,
} from 'react-native/Libraries/NewAppScreen';

import AppleHealthKit, {
  HealthValue,
  HealthKitPermissions,
  HealthInputOptions,
  HealthObserver,
} from 'react-native-health'

const Section: React.FC<{
  title: string;
}> = ({children, title}) => {
  const isDarkMode = useColorScheme() === 'dark';
  return (
    <View style={styles.sectionContainer}>
      <Text
        style={[
          styles.sectionTitle,
          {
            color: isDarkMode ? Colors.white : Colors.black,
          },
        ]}>
        {title}
      </Text>
      <Text
        style={[
          styles.sectionDescription,
          {
            color: isDarkMode ? Colors.light : Colors.dark,
          },
        ]}>
        {children}
      </Text>
    </View>
  );
};

const initHealthKit = () => {
  const permissions = {
    permissions: {
      read: [AppleHealthKit.Constants.Permissions.HeartRate]
    },
  } as HealthKitPermissions

  AppleHealthKit.initHealthKit(permissions, (error: string) => {
    if (error) {
      console.log('[ERROR] Cannot grant permissions!')
    }
    console.log('HealthKit initialized');
  });
};

const configureNativeAppEventEmitter = (setHeartRates: React.Dispatch<React.SetStateAction<HealthValue[]>>) => {
  NativeAppEventEmitter.addListener('healthKit:HeartRate:setup:success', () => {
    console.log('Native listener enabled');
  });

  NativeAppEventEmitter.addListener('healthKit:HeartRate:new', (data: any) => {
    console.log('************ Yaaaaaay', data);

    let options : HealthInputOptions = {
      startDate: new Date(2022, 0, 1).toISOString(),
      type: 'HeartRate' as HealthObserver
    };

    AppleHealthKit.getSamples(options, (err: Object, results: HealthValue[]) => {
      if (err) {
        console.error(err);
        return;
      }
      if (results == null) {
        console.log('Empty results');
        return;
      }
      const heartRates = results.slice(0, 4)
      console.log('HeartRates', heartRates);
      setHeartRates(heartRates)
    });

  });
}

const App = () => {
  const isDarkMode = useColorScheme() === 'dark';
  const [heartRates, setHeartRates] = useState<HealthValue[]>([])

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  initHealthKit();
  configureNativeAppEventEmitter(setHeartRates);

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <Header />
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
          <Section title="Heart Rate">
            {JSON.stringify(heartRates)}
          </Section>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

export default App;
```

**Comment by bodrius** [comment]
same error

**Comment by JDMathew** [comment]
@AnnyFigueira, I believe this is an issue with this commit (https://github.com/agencyenterprise/react-native-health/commit/8d8cb16d91b4ada165a67985235468e5066b9563). It may only be an issue on M1.

**Comment by macelai** [comment]
> @macelai can you please update on this ? Has been opened since a long time

There is no one working actively on this project, we are open to PRs.

**Comment by devpascoe** [comment]
Hey folks. Still getting this, anyone found a work around yet? Rolled back to 1.10.0 for the time being.

**Comment by GGGava** [comment]
This is the same issue as #201. I will close this one as a duplicate to focus the discussion/updates on #201, as it's more active.
