### ISSUE TITLE
InitHealthKit seems to be required each time I kill the app

### ISSUE THREAD

**Issue by batical** [agencyenterprise/react-native-health#18]
**Describe the bug**
First time, when the user click on the button," I want to use the HealthKit feature", I call the InitHealthkit method which prompt the HK page from apple. I accept and I can get step count.

I kill the app, start again. 
- isAvailable method return true
- getStepCount or getDailyStepCountSamples return nothing. I tried to log the result nothing happen
- If I add an initHealthKit method and do the getDailyStepCountSamples it is working.

The problem is I don't want to show the HK permission page from apple without the user asking for it.

**To Reproduce**
See description
**Expected behavior**
I expect the getDailyStepCountSamples to return "at lest something" after killing and restarting an app

**Screenshots**

**Smartphone (please complete the following information):**
simulator : ios14 and iphone11 pro ios14

**Additional context**

**Comment by seidbar** [comment]
Once the user was asked for a specific permission, Apple won't allow the App to ask for that permission again. If your user clicks on the 'I want to use the HealthKit feature' button, they will be asked if they want to give permission for all the read/write permissions detailed in the permissions object. When the user then closes the app and reopens it, they won't be asked for permission again, even if they declined. They would have to go into their settings and change that permission manually.

**Comment by lucaspbordignon** [comment]
Hey @batical! 

As @seidbar said, when you first call `initHealthKit()` method it will prompt the user for the permissions requested. If they decline it, they will need to manually enter the permissions settings in iOS to allow your app to access it

However, when you kill the app and open it again, you should still call the `initHealthKit()` method and if the user was already prompted with the permissions page, it won't show that screen again. It will only read the permissions that the user gave to your app and allow the specific queries to be executed

If you want to avoid users seeing the permissions screen without they requiring it, one alternative would be to call the `initHealthKit()` only when they click a specific button and for the subsequent times you could call it in the background

**Comment by batical** [comment]
it is what I have done. I call it using a button. I am saying the fact I already asked in local storage for now .

Not perfect or what I got in mind, but working
