### ISSUE TITLE
Not listening to HeartRateVariability:new event

### ISSUE THREAD

**Issue by dimitris4** [agencyenterprise/react-native-health#185]
I am trying to implement the background observer for reading HRV data.
It seems like the events are sent, but I am not able to listen to them on the JS side. 
I am getting the following warning in the console: 
WARN  Sending `healthKit:HeartRateVariabilitySDNN:new` with no listeners registered.

The react-native version I'm using is: 0.65.

My AppDelegate.m file: 
<img width="875" alt="Screenshot 2021-11-21 at 11 09 30" src="https://user-images.githubusercontent.com/29309081/142757900-ed5066c1-51c6-43b3-a349-bbffe653c744.png">

The way I try to add the event listener inside the component:
useEffect(() => {
    console.log('add listeners');
    NativeAppEventEmitter.addListener(
      `healthKit:HeartRateVariabilitySDNN:new`,
      () => console.log('new hrv data'),
    );
    return () => {
      NativeAppEventEmitter.removeAllListeners();
    }
  }, []);

Where is the best place to put this code snippet?

**Comment by GGGava** [comment]
This is the same issue as #188 

`NativeAppEventEmitter` is deprecated and is causing this issue, we just updated the [Background Observers documentation](https://github.com/agencyenterprise/react-native-health/blob/master/docs/background.md) with new instructions.

Adding a listener with `NativeEventEmitter(NativeModules.AppleHealthKit).addListener(...)` should solve this issue.

```javascript
new NativeEventEmitter(NativeModules.AppleHealthKit).addListener(
      'healthKit:HeartRate:new',
      async () => {
        console.log('--> observer triggered');
      },
    );
```
