### ISSUE TITLE
Background Observers Issue

### ISSUE THREAD

**Issue by powerlinx-digicode** [agencyenterprise/react-native-health#188]
**Describe the bug**
No listeners registered warnings when listeners are registered.

**To Reproduce**
1. Follow steps described here: https://github.com/agencyenterprise/react-native-health/blob/master/docs/background.md
2. Implement listeners with following types: 'healthKit:StepCount:setup:success', 'healthKit:StepCount:setup:failure', 'healthKit:StepCount:new'

**Expected behavior**
Listeners work correctly

**Screenshots**
Listeners do not work. Getting warning messages (see screenshot)
![Screenshot 2021-12-01 at 13 58 29](https://user-images.githubusercontent.com/71374589/144230879-e7bbade1-46d4-4825-815a-dd5c063180e3.png)

**Smartphone (please complete the following information):**

- Device: iPhone11
- OS: IOS 15.0

- Version: 1.12.0

**Additional context**

**Comment by chramos** [comment]
same issue here

**Comment by amerdiglisic** [comment]
same issue here

**Comment by cdavid138** [comment]
Getting the issue here also, did any of you find a solution?

**Comment by millro04** [comment]
Same thing here!

**Comment by CaptainJeff** [comment]
Same here! Anyone find a solution?

**Comment by junedomingo** [comment]
Same here!

I'm on version 1.13.0
RN: 67.4
R: 17.0.2

**Comment by KiranRadish** [comment]
does anyone found solution for this?

**Comment by GGGava** [comment]
`NativeAppEventEmitter` is deprecated and is causing this issue, we just updated the [Background Observers documentation](https://github.com/agencyenterprise/react-native-health/blob/master/docs/background.md) with new instructions.

Adding a listener with `NativeEventEmitter(NativeModules.AppleHealthKit).addListener(...)` should solve this issue.

```javascript
new NativeEventEmitter(NativeModules.AppleHealthKit).addListener(
      'healthKit:HeartRate:new',
      async () => {
        console.log('--> observer triggered');
      },
    );
```
