### ISSUE TITLE
Duplicate getWorkout / getSamples code

### ISSUE THREAD

**Issue by Frans-L** [agencyenterprise/react-native-health#20]
There are now two ways to fetch workout data.

One option is to use [getSamples](https://github.com/agencyenterprise/react-native-health/blob/master/docs/getSamples.md) and the other option is to use [getWorkout](https://github.com/agencyenterprise/react-native-health/blob/master/docs/getWorkout.md).

There is duplicate Objective C code because of that. One of them should be removed.  getSamples returns more data currently, such as "sourceName" & "sourceId", so in some sense getSamples is a bit better now.

The duplicated parts seem to come from this pull request: [Add workout (read / write) cholesterol (read) authorization check for each health kit type](https://github.com/terrillo/rn-apple-healthkit/pull/41/files). The weird part is that the pull request hasn't been merged to this repository. 

Nevertheless, that same exact code seems to come from here: [Pull request #1 from nutrisense/feature/workout-read-write](https://github.com/agencyenterprise/react-native-health/commit/73d7dfca0d00e9c5c8bca5722b9ce01226974590).

The difficult part is that the pull request also includes some other changes which are not related to reading workout data. So, reverting the changes is difficult.

My suggestion is to remove the function **getWorkout** and Objective C code that is related to it.

**Comment by lucaspbordignon** [comment]
Hey @Frans-L!

That's a good point, didn't realize we had this duplicate. I agree with you that we should prioritize `getSamples` over `getWorkout` as it has more flexibility to the library

Also, the latest one doesn't have documentation, so we don't need to spend our workforce adding it too

I'll create a new PR for that shortly
