### ISSUE TITLE
Logout/signout functionality is not added 

### ISSUE THREAD

**Issue by MUZAFFAR-PURELOGICS** [agencyenterprise/react-native-health#221]
Hi,
Kindly add Logout / sign-out functionality in to this package. 
User can sign-out and use different account of health-kit.

**Comment by ryanb93** [comment]
There are no concepts of accounts in HealthKit, each device has a single data store. The member must go into the Health application to disable access to individual applications, there is no way to bring up the permissions screen a second time once shown without uninstalling and reinstalling the app.

**Comment by RuanAzevedo** [comment]
I am closing this issue since its being inactive for a while. Please, feel free to reopen it if you have more questions about it.
