### ISSUE TITLE
Poor Error Handling

### ISSUE THREAD

**Issue by Frans-L** [agencyenterprise/react-native-health#25]
**Is your feature request related to a problem? Please describe.**

When the library is fetching something and fails, only a vague description is sent to React Native.

Example from **fitness_getSamples**:
```objective-c
            NSLog(@"error getting samples: %@", error);
            callback(@[RCTMakeError(@"error getting samples", nil, nil)]);
```

React Native jus receives _"error getting samples"_. There's no way to see what the actual reason for the error is.

**Describe the solution you'd like**

The better way is to forward the actual error msg to React Native. 
Example from **initializeHealthKit**.
```objective-c
            NSString *errMsg = [NSString stringWithFormat:@"Error with HealthKit authorization: %@", error];
            NSLog(errMsg);
            callback(@[RCTMakeError(errMsg, nil, nil)]);
```

This way the actual error message can be seen.

**Additional context**

There are in total 13 different cases where the error is not forward to React Native. I'm not so familiar with Objective C, that's why I'm not sure what is the best way to fix this issue. (Copy pasting the same improved error logic 13 times doesn't sound like a proper solution.)

**Comment by lucaspbordignon** [comment]
Definitely! That's something we've been struggling for some time when debugging the library

I just added the `help wanted` tag to the library, so we can have some extra pair of hands to work on it. We should also revisit all the methods implemented to make sure we have captured exceptions in all of them

**Comment by GGGava** [comment]
I'm taking a look into this one
