### ISSUE TITLE
undefined is not a function (near '..._reactNativeHealth.default.initHealthKit...')

### ISSUE THREAD

**Issue by m-ruhl** [agencyenterprise/react-native-health#27]
Hey,

I wanted to use the plugin and copied the snippet:

```js
import AppleHealthKit, { HealthKitPermissions } from "react-native-health";
...
AppleHealthKit.initHealthKit(permissions, (error: string) => {
...
```

But this seems to cause an error:
`TypeError: undefined is not a function (near '..._reactNativeHealth.default.initHealthKit...')`

Any ideas to solve it?

Thanks
Michael

**Comment by TowhidKashem** [comment]
Had the same issue but got it to work after manual linking. Not really a solution though so don'y close the issue.

**Comment by TowhidKashem** [comment]
I had to do this part after `pod install` to get it to work:

> Update the ios/<Project Name>/info.plist file in your project

```
<key>NSHealthShareUsageDescription</key>
<string>Read and understand health data.</string>
<key>NSHealthUpdateUsageDescription</key>
<string>Share workout data with other apps.</string>
```

May also need to uninstall/re-install the app after the change.

**Comment by m-ruhl** [comment]
Thanks for the hint..

I didn't had the second (update) entry, as my app should only read data..
So maybe the documentation needs to be improved

**Comment by lucaspbordignon** [comment]
Hey @m-ruhl!

First of all, sorry for the late response.

Secondly, as @TowhidKashem mentioned, this step is really required for both reading and writing operations in HealthKit. Just merged the updates from #30 into master, so the steps are clearer

**Comment by blakete** [comment]
> I had to do this part after `pod install` to get it to work:
> 
> > Update the ios//info.plist file in your project
> 
> ```
> <key>NSHealthShareUsageDescription</key>
> <string>Read and understand health data.</string>
> <key>NSHealthUpdateUsageDescription</key>
> <string>Share workout data with other apps.</string>
> ```
> 
> May also need to uninstall/re-install the app after the change.

Added this to my app.json file as seen here: 
```
{
  "expo": {
    "name": "AwesomeProject",
    "slug": "AwesomeProject",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "infoPlist": {
        "NSCameraUsageDescription": "This app uses the camera to scan barcodes on event tickets.",
        "NSHealthShareUsageDescription": "Read and understand health data",
        "NSHealthUpdateUsageDescription": "Share workout data with other apps."
      }
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      }
    },
    "web": {
      "favicon": "./assets/images/favicon.png"
    }
  }
}
```
Still does not work for me as I see the message:
```
TypeError: undefined is not a function (near '..._reactNativeHealth.default.initHealthKit...')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

**Comment by varsh8th** [comment]
Hey @m-ruhl @TowhidKashem @lucaspbordignon @blakete 

facing the same issue for an expo app, was there any fix to this ?
There's not much documentation wrt expo, so its been hard navigating this, any help is appreciated :)

**Comment by MrLucasapl** [comment]
I'm having the same error but I'm using expo and even though I followed the steps in the link
https://github.com/agencyenterprise/react-native-health/blob/master/docs/Expo.md

I still get the error

TypeError: _reactNativeHealth.default.initHealthKit is not a function (it is undefined), js engine: hermes

Does anyone have a solution for expo?

**Comment by asfaqehussain** [comment]
I'm also facing the same issue while working with Expo, is there any update on the bug and how that can be resolved.

**Comment by DreamEmulator** [comment]
Bumping this 😕

Thanks if someone can post a solution. I wonder if it has something to do with the New Architecture..

**Comment by AkaCoder404** [comment]
Same issue with Expo and new architecture.

**Comment by asfaqehussain** [comment]
I did the Pod install in the project for expo and then tried to clean and start from the XCode than it worked.
Also, I added the condition of isDevice that it should run only on real devices. 
On simulators, It shows an error and won't run.

**Comment by KevinAHudson** [comment]
> Same issue with Expo and new architecture.

had this issue as well when testing and when building with npx expo run:ios was getting a conflict with react CLE and react Health both having duplicate hasListener symbols.  went into RCTAppleHealthKit.m changed it to a static bool type for that variable and was able to build and access healthkit on expo workflow.

**Comment by karshten** [comment]
@KevinAHudson what did you exactly do to solve this problem I do not have such file in /ios folder

**Comment by umarfarooqfastn** [comment]
> I had to do this part after `pod install` to get it to work:
> 
> > Update the ios//info.plist file in your project
> 
> ```
> <key>NSHealthShareUsageDescription</key>
> <string>Read and understand health data.</string>
> <key>NSHealthUpdateUsageDescription</key>
> <string>Share workout data with other apps.</string>
> ```
> 
> May also need to uninstall/re-install the app after the change.

where we have to this in <array> ... </array> ?

**Comment by KevinAHudson** [comment]
> [@KevinAHudson](https://github.com/KevinAHudson) what did you exactly do to solve this problem I do not have such file in /ios folder

Sorry..  I had to access this file through xCode and not through VsCode.  this should fix your problem although not gracefully..

**Comment by Schotsl** [comment]
I'm having the same issue :(

**Comment by Schotsl** [comment]
Changing `"newArchEnabled": true,` to `"newArchEnabled": false,` in the `app.json` fixes the issue, altough it does revert you to the old architecture.

**Comment by inform880** [comment]
> Changing `"newArchEnabled": true,` to `"newArchEnabled": false,` in the `app.json` fixes the issue, altough it does revert you to the old architecture.

@Schotsl 
I tried this and it hasn't worked for me unfortunately. Any other specific things you did to get it to work? I've tried everything I could think of

**Comment by Schotsl** [comment]
Noo, besides that, I really didn't do anything new. This might be a redundant comment, but you did rebuild the entire app after switching to the new architecture, right? :)

**Comment by inform880** [comment]
yeah, went as far as basically wiping the entire ios folder and making sure all the entitlements were there, etc. I do wish this repo would get a bit of love, I'd do it but Apple Health was a fringe requirement for what I'm working on unfortunately. 

edit: as I was posted that reply I was trying a complete rebuild again and it worked this time!

**Comment by mpho-ppm** [comment]
I am experiencing the same issue too on Expo 52. The only way I can get it to work is by disabling `newArchEnabled` on the app.json file but that means I'm losing out on updates that Expo has implemented when `newArchEnabled` is enabled. Has there been any updates to `react-native-health`?

**Comment by Deveshb15** [comment]
anyone found how to fix this? i tried making the newArchEnabled to false as well but still didn't work @mpho-ppm

**Comment by amandeep-se** [comment]
I am doing it in CLI, not working same issue I am facing. Question to those people who has run it successfully are you guys using Expo?

Please help how to solve this TypeError: _reactNativeHealth.default.initHealthKit is not a function (it is undefined),

**Comment by bayush-9** [comment]
I used a workaround. People using CLI and new architecture may find it helpful. 
```
import BrokenHealthKit, {
  HealthKitPermissions,
  HealthValue,
} from 'react-native-health';

const NativeModules = require('react-native').NativeModules;
const AppleHealthKit = NativeModules.AppleHealthKit as typeof BrokenHealthKit;
AppleHealthKit.Constants = BrokenHealthKit.Constants;
```
