### ISSUE TITLE
Duplicate case value 'HKCategoryValueSleepAnalysisAsleep'

### ISSUE THREAD

**Issue by kjqtech** [agencyenterprise/react-native-health#274]
I am facing below issue while run app in ios 

<img width="523" alt="Screenshot 2023-01-09 at 6 48 58 PM" src="https://user-images.githubusercontent.com/52341142/211318154-cd906320-f23a-49f5-9668-2a4135eda427.png">
.githubusercontent.com/52341142/211318120-64f4c6b0-d821-4893-9cb7-c5ec16797982.png">

<img width="525" alt="Screenshot 2023-01-09 at 6 49 10 PM" src="https://user-images.githubusercontent.com/52341142/211318201-da2c58b1-0737-42a9-984f-a0ddc284b930.png">

<img width="504" alt="Screenshot 2023-01-09 at 6 47 02 PM" src="https://user-images.githubusercontent.com/52341142/211318671-c590024c-6788-4c1c-bad9-cffe350a75cc.png">

please do help me here 

i am using 
"react-native": "0.66.4"
"react-native-health": "^1.13.0",

**Comment by Monir-Shembesh** [comment]
it was introduced with this [PR](https://github.com/agencyenterprise/react-native-health/pull/247)

**Comment by StephenChanKK** [comment]
my solution: comment out the "case" to let it work first

**Comment by darshankacha** [comment]
Please use xcode version 14 and ios 16 🥳

**Comment by GGGava** [comment]
Hello, you need to update your Xcode to >=14.0.0. If you cannot, I suggest doing as StephenChanKK suggested and comment out these cases.
