### ISSUE TITLE
Estimating calories based on heart rate

### ISSUE THREAD

**Issue by G2Jose** [agencyenterprise/react-native-health#313]
This may be slightly off topic, but I'm curious if folks here have any thoughts on how best to get the active energy spent in a workout using this library. 

I can't be a 100% sure, but it seems to me like some weight training apps I've used rely on apple health to compute the calories I burn using my apple watch, using the heart rate sensor. 

- Is something like this possible using this or a related library? 
- Does anyone have general tips on ways to compute energy spent in a weight training workout?

**Comment by GGGava** [comment]
Hey @G2Jose do you want to specifically get this through Heart Rate? HealthKit provides access to the Active Energy data from apple watch, you can use [this function](https://github.com/agencyenterprise/react-native-health/blob/master/docs/getActiveEnergyBurned.md)

AFAIK Apple doesn't disclose how they calculate this info though, check this thread: https://apple.stackexchange.com/questions/344653/how-does-healthkit-calculate-activeenergyburned-and-other-variables

I'll close this issue as resolved but let me know if you need any help
