### ISSUE TITLE
[Question] Do `getSamples` method work on emulator?

### ISSUE THREAD

**Issue by krakz999** [agencyenterprise/react-native-health#32]
I'm using the emulator to test my app. I have logged 2 workout entries manually in the Apple Health app, but `getSamples()` does not return anything.

Do `getSamples` method work on emulator or maybe there is another issue?

**Comment by Frans-L** [comment]
It works at least with a version using v.1.1.5. Tested today. 
(I would guess that it works also with 1.2.0.)

**Comment by krakz999** [comment]
> It works at least with a version using v.1.1.5. Tested today.
> (I would guess that it works also with 1.2.0.)

The issue was I missed the `type` property from the options. 

```
 let options = {
    startDate: date,
    endDate: to.toISOString(),
    type: AppleHealthKit.Constants.Observers.Workout,
  } as HealthInputOptions;
```

Works now, thanks for getting back so quick!
