### ISSUE TITLE
Clinical Records issue

### ISSUE THREAD

**Issue by ngocht143** [agencyenterprise/react-native-health#320]
Hi team,
We are using this library for a long time to get user's health data such as HeartRate, Height, Weight, Steps, BMI, BloodPressure. But recently the Apple team reviewers rejected our app with reason: 

> "Your app uses the Clinical Health Records API but your app does not appear to include any primary features that require the Clinical Health Records API.
> 
> Next Steps
> To resolve this issue, please remove the Clinical Health Records API from your app, as well as any references to this app’s interactivity with Clinical Health Records from your app or its metadata. 
> To disable the functionality through App Store Connect, please uncheck the "Health Records" capability (leaving the HealthKit entitlement enabled), remove all the references to HKClinicalRecord class from your code, then resubmit."
> 

although we do not using these apis (We don't check the Clinical Health Records and Background Delivery capabilities).

So is there a way for this library to detach Clinical Records module?
Looking forward to see your reply.
Thanks in advanced./.

**Comment by DeepikaSharma5** [comment]
<img width="780" alt="image" src="https://github.com/agencyenterprise/react-native-health/assets/64214744/628f9d07-929c-4e40-834c-3b49c1890569">
Remove this `Clinical Health Records` from your` Signing & Capabalities`. Rebuild and upload the app. Then it will be fine

**Comment by ngocht143** [comment]
@DeepikaSharma5 I did it but it's still rejected. I think the problem is in native code with HKClinicalRecord class and the Apple reviewers detected it.

**Comment by GGGava** [comment]
Hello @ngocht143, detaching the clinical records to a module is currently a bit complicated, but you could try to run a build script (maybe you can do it as a post-install script in the podfile) to remove the clinical records code.

You can change the `clinicalTypeFromName` method to only return nil, and completely remove the `fetchClinicalRecordsOfType` function and the `getClinicalRecords` RCT export block.

Sorry, I'm not sure if this is the optimal solution but should work

Running a bash script through podfile: https://stackoverflow.com/questions/26326762/run-bash-command-in-cocoapods-post-install-step

**Comment by datamond** [comment]
same issue 😭

**Comment by ravidubeygit** [comment]
did any one found solution for this issue ??

**Comment by DeepikaSharma5** [comment]
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/64214744/251358899-628f9d07-929c-4e40-834c-3b49c1890569.png"> Remove this `Clinical Health Records` from your` Signing & Capabalities`. Rebuild and upload the app. Then it will be fine

I had the same issue. My app was rejected for a week and I tried everything. I event tried to modify the package natively. But Then I did the above change.

1. Untick the "Clinical Health Records".
2. Delete podfile.lock
3. Delete thenode_modules
4. npm install
5. Then pod install
6. In XCode rebuild the project
7. Submit the new build as a new version.

After these steps my app got approved. Remember you need to add the new build as a new version. Please try this and let me know.

**Comment by Hooman-studio** [comment]
I am getting the same error using expo development build

<details><summary>Apple rejection reason</summary>
<p>


Your app still uses the Clinical Health Records API but your app does not appear to include any primary features that require the Clinical Health Records API.

Next Steps

To resolve this issue, please remove the Clinical Health Records API from your app, as well as any references to this app’s interactivity with Clinical Health Records from your app or its metadata. 

To disable the functionality through App Store Connect, please uncheck the "Health Records" capability (leaving the HealthKit entitlement enabled), remove all the references to HKClinicalRecord class from your code, then resubmit.

</p>
</details> 

This is my app.config.ts

```typescript
   [
      "react-native-health",
      {
        healthSharePermission:
          "Share your health data with medical professionals at Pulsia, please allow Pulsia to access your health data.",
        healthUpdatePermission:
          "Share your health data with medical professionals at Pulsia, please allow Pulsia to access your health data.",
      },
    ],
``` 

How can i remove the clinical health records API for eas builds?
