### ISSUE TITLE
how can we get multiple or all health data in a short way?

### ISSUE THREAD

**Issue by nHussain18** [agencyenterprise/react-native-health#326]
I am working on an app in which I want to show all the health kit data, so is there any way that I can get all the data using a single function. I can get different data using different functions but it gets lengthy and will take more time to load,
I was wondering in the documentation but I can't found such a function to get multiple data.

**Comment by GGGava** [comment]
Hey @nHussain18 unfortunately there is no way to get all healthkit data with a single function, as this is currently not supported by Apple's Healthkit.
