### ISSUE TITLE
Docs Offline

### ISSUE THREAD

**Issue by fansilva1991** [agencyenterprise/react-native-health#328]
**Describe the bug**
It looks like the docs for the project are offline. When opening the URL at the home of the GitHub project, it does not display the docs.

**To Reproduce**
Open the following URL:

[docs.react-native-health.com](https://docs.react-native-health.com/)

**Expected behaviour**
It should open the project docs correctly.

**Screenshots**
![Screenshot 2023-08-04 at 7 47 36 PM](https://github.com/agencyenterprise/react-native-health/assets/4633618/b38511bd-dcc5-4d5c-bf4e-d4e46c490fac)

**Comment by GGGava** [comment]
Hey, thanks for that, this is actually an old link that was left in the readme, thank you
