### ISSUE TITLE
Gitbook link redirects to phishing site

### ISSUE THREAD

**Issue by gewfy** [agencyenterprise/react-native-health#335]
Hi and thank you for a great lib!

This link:
https://github.com/agencyenterprise/react-native-health/blob/ba277108369a259c37b4c782ea93e949e30ed9a1/docs/README.md?plain=1#L2-L4
Leads to some kind of phising site.

**Comment by GGGava** [comment]
Hey, thanks for that, this link was removed from the repo readme but was left in this readme, I'll remove it, thank you very much :)
