### ISSUE TITLE
Unknown type name 'RCTCallableJSModules'

### ISSUE THREAD

**Issue by Oodebalan** [agencyenterprise/react-native-health#336]
I have followed the steps in order to install react-native-health (yarn add, pod install, update info.plist, add Healthkit support to my application's Capabilities)
I have "react-native-health": "^1.18.0"

When running my application from xcode I get a type error with `RCTCallableJSModules`

<img width="518" alt="Capture d’écran 2023-09-10 à 11 53 25" src="https://github.com/agencyenterprise/react-native-health/assets/24439708/244b59f4-8d5c-42c5-8105-423f557fb8aa">

**Comment by Oodebalan** [comment]
Hey Gava, thanks for you reply

I have try this but it's still not working. I couldn't find any reason for this issue to happen..

**Comment by GGGava** [comment]
Did you find out what happened? @Oodebalan

**Comment by rishabhkumar-vibe** [comment]
ww

**Comment by Rk5422686** [comment]
**RCTCallableJSModules** API for NativeModules was introduced in **React Native** version **0.66.0.** Thus, to address this issue, it's necessary to upgrade your app to version 0.66 or later.
