### ISSUE TITLE
getBodyFatPercentageSamples coming back as undefined 

### ISSUE THREAD

**Issue by hammad0316** [agencyenterprise/react-native-health#34]
**Describe the bug**
Calling the getBodyFatPercentageSamples() throws errors. 
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not a function (near '..._reactNativeHealth.default.getBodyFatPercentageSamples...')
```

**Comment by lucaspbordignon** [comment]
Hey @hammad0316!

Thanks for the submission. Realized that the existing implementation for  `getBodyFatPercentageSamples()` is not being exported for the React Native interface

Added a fix for that in #37
