### ISSUE TITLE
[Bug] Xcode 12 Support - React-Core dependency

### ISSUE THREAD

**Issue by dylmye** [agencyenterprise/react-native-health#36]
Happy new year :)

Are you planning to update your dependency on React to React-Core? See https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

I haven't specifically tested your package on Xcode 12 as I don't have a physical device to test with but it should be an easy change to test and implement. I'm happy to submit a PR to test if that helps.

**Comment by NS-BOBBY-C** [comment]
Happy New Year!

Is this still an issue? I just created a PR with an example react-native app (#44) with the latest version of react-native. I had no problem using Cocoapods to install the project.

**Comment by dylmye** [comment]
Seems like it still works, my bad. Thanks for looking into this @NS-BOBBY-C !
