### ISSUE TITLE
How can I get oxygenSaturation?

### ISSUE THREAD

**Issue by mnakai** [agencyenterprise/react-native-health#38]
oxygenSaturation
https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifier

Isn't it wrong to think that the items on this page can be obtained by HealthKit?
If it doesn't seem to be supported yet, please do so. Thank you.

**Comment by Macelai** [comment]
This is now available by #51

**Comment by mnakai** [comment]
Thank you!!
