### ISSUE TITLE
Getting empty array with getDailyStepCountSamples

### ISSUE THREAD

**Issue by potatoengineer** [agencyenterprise/react-native-health#41]
I have manually added steps on the simulator Health app and the data source is showing my app and all the Health permissions are on but when I try to getDailyStepCountSamples, I get an empty array.

Also, another issue I have is that I need to initiate HealthKit each time before getting the empty array otherwise I get 'undefined'. Once I initiate HealthKit again, it will return 'undefined' AND log 'Steps: []'. 

```
import AppleHealthKit from 'react-native-health';

export function useHealthKit({
    init = false,
    steps = false,
}) {
    const PERMS = AppleHealthKit.Constants.Permissions;

    const initiate = () => {
        let permissions = {
            permissions: {
                read: [
                    PERMS.StepCount,
                ],
            },
        };
        AppleHealthKit.initHealthKit(permissions, (err, results) => {
            if (err) {
                console.log(err);
            } else {
                console.log('Initialized!', results),
            }
        });
    };

    const getSteps = () => {
        let stepOptions = {
            startDate: new Date(2021, 1, 1).toISOString(),
        };
        AppleHealthKit.getDailyStepCountSamples(
            stepOptions,
            (err, results) => {
                if (err) {
                    return;
                }
                console.log('Steps: ', results);
            },
        );
    };
    init && initiate();
    steps && getSteps();
}
```

It is called by the following: 
```
const SomeView = () => {
    <View>
      <Button onPress={() => useHealthKit({init: true})>
        <Text>Initiate HealthKit</Text>
      </Button>
      <Button onPress={() => console.log(useHealthKit({steps: true}))>
        <Text>Console.log steps</Text>
      </Button>
    </View>
};
```

**Comment by HugoChengMyC** [comment]
im noticing the same thing happen with getSamples` let today = new Date();
                    let weekAgo = new Date(today.setDate(today.getDate() - 2));


                    let options = {
                        startDate: weekAgo.toISOString(),
                        endDate:   today.toISOString(),
                        type:'Walking'
                    };

                    console.log('weekAGO',options)
                    //for demo purposes display whay the weekly step counts will be 
                    AppleHealthKit.getSamples(options, (error, stepResults) => {
                        if (error) {
                            console.log('ERROR', error);
                            return;
                        }
                        console.log('DEBUG STEP COUNTER DATA', stepResults);


                        setData(stepResults.value);
                    });`

**Comment by stratosEft** [comment]
Hi all, I think the docs are deprecated in some areas and some valid ones would be helpful. I managed to retrieve samples by adding moment.js and a fixed format (ISOString didn't work)

```
const startDate = moment('2021-02-02', 'YYYY-MM-DD').format(
        'YYYY-MM-DDTHH:mm:ss.SSSZZ',
      );
```

**Comment by Macelai** [comment]
Hey, I tested with the example project that was created recently and it's working fine.

Something like this: 

```javascript
const permissions = {
  permissions: {
    read: [AppleHealthKit.Constants.Permissions.StepCount],
    write: [AppleHealthKit.Constants.Permissions.StepCount],
  },
} as HealthKitPermissions;

AppleHealthKit.initHealthKit(permissions, (error: string) => {
  /* Called after we receive a response from the system */

  if (error) {
    console.log('[ERROR] Cannot grant permissions!');
  }
});

export default function App() {
  const [authStatus, setAuthStatus] = useState<any>({});

  const handlePressGetAuthStatus = () => {
    let stepOptions = {
      startDate: new Date(2021, 1, 1).toISOString(),
    };
    AppleHealthKit.getDailyStepCountSamples(stepOptions, (err, result) => {
      if (err) console.error(err);
      setAuthStatus(result);
    });
  };

  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}>
          <View style={styles.body}>
            <View style={styles.sectionContainer}>
              <Text style={styles.sectionTitle}>
                React Native Health Example
              </Text>
              <Text onPress={handlePressGetAuthStatus}>
                Press me to get Auth Status
              </Text>
              <Text style={styles.sectionDescription}>
                {JSON.stringify(authStatus, null, 2)}
              </Text>
            </View>
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
}
```

**Comment by AlbertoMeQ** [comment]
I agree there is an issue with using the Date object directly. I managed by using Date.now() and subtracting whatever time period I needed.
