### ISSUE TITLE
Cannot Ask Permission to call getDistanceSwimming

### ISSUE THREAD

**Issue by pocketcat** [agencyenterprise/react-native-health#49]
I am able to successfully request AppleHealthKit.Constants.Permissions.DistanceCycling and AppleHealthKit.Constants.Permissions.DistanceWalkingRunning but there is no "AppleHealthKit.Constants.Permissions.DistanceSwimming". Could you please help me with this? Thanks!

**Comment by lucaspbordignon** [comment]
Hey @pocketcat! Welcome to the project

I'm investigating the issue and seems that we don't have the `DistanceSwimming` permission under the `Permissions` list. Could you try passing the string itself to the initialization method and check if that works?

Would be like

```typescript
...

/* Permission options */
const permissions = {
  permissions: {
    read: [ 'DistanceSwimming' ],
    write: [ 'DistanceSwimming' ],
  }
} as HealthKitPermissions


AppleHealthKit.initHealthKit(permissions, () => {
  ...
});

...
```
