### ISSUE TITLE
Asking experiences about Velocity & Step & Distance & Calories burned

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [agencyenterprise/react-native-health#61]
Thanks in advances...

Nice to meet you! 
i'm thinking about feature call "Calories burned".
But after some days of asking people iPhones, i saw that not many people have appleWatch or some wearable else to activate energy Feature of HealthKit.
for research about calories formulas for calories calculating

Asking some experiences about Velocity & Step & Distance & Calories burned and solutions.

Thanks!

**Comment by lucaspbordignon** [comment]
Hey @NguyenHoangMinhkkkk!

Not sure I understood the problem, do you mind expanding it a bit?

If that helps, we do have methods for

1. [Active Energy (or active calories)](https://github.com/agencyenterprise/react-native-health/blob/master/docs/getActiveEnergyBurned.md)
2. [Basal Energy (or resting calories)](https://github.com/agencyenterprise/react-native-health/blob/master/docs/getBasalEnergyBurned.md)

**Comment by NguyenHoangMinhkkkk** [comment]
> Hey @NguyenHoangMinhkkkk!
> 
> Not sure I understood the problem, do you mind expanding it a bit?
> 
> If that helps, we do have methods for
> 
> 1. [Active Energy (or active calories)](https://github.com/agencyenterprise/react-native-health/blob/master/docs/getActiveEnergyBurned.md)
> 2. [Basal Energy (or resting calories)](https://github.com/agencyenterprise/react-native-health/blob/master/docs/getBasalEnergyBurned.md)

Thanks!
i did use those methods and if i have data of Step & Distance but not Energies... 
then have to calculate energy burned by some methods, that's what i am reseaching for.
