### ISSUE TITLE
Add support to clinical types (medication, allergy...)

### ISSUE THREAD

**Issue by macelai** [agencyenterprise/react-native-health#69]
See https://developer.apple.com/documentation/healthkit/hkclinicaltype

**Comment by apstone** [comment]
I would love to help out with this, but may require a bit of direction!

**Comment by apstone** [comment]
Thanks a ton @lucaspbordignon! I'm on it 😎

**Comment by klandell** [comment]
Hello!  Is there any progress on this?

**Comment by klandell** [comment]
I've started looking into implementing this as well!  I'll create a PR if I get anywhere.
