### ISSUE TITLE
Add documentation to workout methods

### ISSUE THREAD

**Issue by lucaspbordignon** [agencyenterprise/react-native-health#7]
Add documentation to workout methods

- `saveWorkout`

We currently have an implementation for them, but the documentation is missing

### Note

The `getWorkout` method is being deprecated in favour of `getSamples` - See #20

**Comment by TDDR** [comment]
Hello, could you assign this issue to me please?

**Comment by lucaspbordignon** [comment]
Hey @TDDR! For sure, just added you as an assignee. Let me know if you need any help with this one

**Comment by TDDR** [comment]
Hey @lucaspbordignon, I have been looking into the code trying to figure out the implementation. After looking into the documentation a little closer I was just wondering if I actually need to own a HealthKit in order  to properly document it?

**Comment by lucaspbordignon** [comment]
Hey @TDDR and @seidbar! I'm also not sure what exactly you mean with owning a HealthKit, could you clarify that for us?

Regarding documenting it though, you need a device with HealthKit in order to test the functionality itself, whether a physical iPhone or a simulator

As @TDDR mentioned, we do need also to add the capabilities to Xcode in order for the library to have access to the HealthKit. We do have a [section](https://github.com/agencyenterprise/react-native-health#manual-installation) that describes this need, but we should definitively make it more explicit

**Comment by seidbar** [comment]
If step 6 of the mentioned section would move up to the 'Getting started' section that should suffice to get started.

A sample project would be neat. I put something together using functional components and would gladly participate in enhancing the documentation as I use the package more thoroughly.

**Comment by seidbar** [comment]
> Hey @TDDR and @seidbar! I'm also not sure what exactly you mean with owning a HealthKit, could you clarify that for us?
> 
> Regarding documenting it though, you need a device with HealthKit in order to test the functionality itself, whether a physical iPhone or a simulator
> 
> As @TDDR mentioned, we do need also to add the capabilities to Xcode in order for the library to have access to the HealthKit. We do have a [section](https://github.com/agencyenterprise/react-native-health#manual-installation) that describes this need, but we should definitively make it more explicit

I proposed a change to resolve this.

**Comment by lucaspbordignon** [comment]
@TDDR No problem with that! We have an [open issue](https://github.com/agencyenterprise/react-native-health/issues/10) to create a sample project for the library. We might be able to have that running using [Expo Snack](https://snack.expo.io/) or anything related, so we don't require everybody to have an iPhone to play around with the library

But thank you for the support still! Let us know if have any additional idea for the project or you eventually feel ready to contribute to it! :)

**Comment by Frans-L** [comment]
Note: **getWorkout** and **getSamples** can be used to fetch workouts. One of them should be removed to eliminate duplicate code. Issue about it: https://github.com/agencyenterprise/react-native-health/issues/20
