### ISSUE TITLE
getSamples() with type="Walking" always return error

### ISSUE THREAD

**Issue by yfng96** [agencyenterprise/react-native-health#71]
**Describe the bug**
As stated in document, getSamples() can support type ['Walking', 'StairClimbing', 'Running', 'Cycling', 'Workout']
However, when calling the getSamples() with type="Walking", an error message is returned, which is "error getting samples". 

The getSamples() for other types can work well. By the way, if we put type="Running", we can get the walking data too.
Is getSamples() support "Walking"?

**To Reproduce**
let options = {
  startDate: (new Date(2021,3,12)).toISOString(),
  endDate: (new Date()).toISOString(),
  type: 'Walking',
};

AppleHealthKit.getSamples(options, (err, results) => {
  if (err) {
    console.log('error: ', err)
  }
  console.log(results)
});

**Expected behavior**
Return array that contain walking data

**Comment by stratosEft** [comment]
`let samplesOptions = {
      type: 'Walking', // one of: ['Walking', 'StairClimbing', 'Running', 'Cycling', 'Workout']
      startDate: startOfWeek.toISOString(true),
      ascending: true,
    };`
    
    I get walking samples with the options above. (startOfWeek is the Monday of a user's selected day). Check HK initialization and in simulator doesn't work for me. Need an actual Iphone

**Comment by yfng96** [comment]
So the problem is because of the simulator? Currently I don't have actual device to test, is there any other solution to deal with this issue? Other options can work well, just the "Walking" has problem.

**Comment by GGGava** [comment]
Hey @yfng96 

I tried your steps to reproduce in the simulator and it worked fine. Could you double check your read authorizations?

**Comment by yfng96** [comment]
Hi, @GGGava

These are the read permissions declared
```
 const PERMS = AppleHealthKit.Constants.Permissions;
    const permissions = {
      permissions: {
        read: [
          PERMS.DistanceCycling,
          PERMS.DistanceWalkingRunning,
          PERMS.ActiveEnergyBurned,
          PERMS.AppleExerciseTime,
          PERMS.Workout,
          PERMS.DistanceSwimming,
        ],
      },
    };
```

Is there any missing permission?

**Comment by GGGava** [comment]
Try including `StepCount`

**Comment by yfng96** [comment]
@GGGava ur solution is worked! Thank you very much
