### ISSUE TITLE
Accessing data from "Nutrition" is not possible for anything except "Carbohydrates"

### ISSUE THREAD

**Issue by fakeheal** [agencyenterprise/react-native-health#72]
**Describe the bug**
Requesting "read" permissions for any dietary data but "Carbohydrates" doesn't work.

**To Reproduce**

```
const permissions = {
  permissions: {
    read: [
      AppleHealthKit.Constants.Permissions.ActiveEnergyBurned, // THIS IS OK
      AppleHealthKit.Constants.Permissions.BasalEnergyBurned, // THIS IS OK
      AppleHealthKit.Constants.Permissions.EnergyConsumed, 
      AppleHealthKit.Constants.Permissions.Protein,
      AppleHealthKit.Constants.Permissions.BodyMass, // THIS IS OK
      AppleHealthKit.Constants.Permissions.BodyFatPercentage, // THIS IS OK
    ],
    write: [],
  },
};
```

**Expected behavior**
After doing: 

```
AppleHealthKit.initHealthKit(permissions, (error: string) => {
  if (error) {
    console.log(error);
    console.log('[ERROR] Cannot grant permissions!');
  }
});
```

To be presented with a screen that includes the permissions requested (and described in the `permissions` array).

**Screenshots**
Here's a screenshot of code & emulator:
![screenshot](https://i.imgur.com/LhX6oye.png)

**Smartphone (please complete the following information):**

- Device: Simulator:  iphone 12 mini
- OS: 14.4
- Version idk

**Additional context**
I copy pasted all available permission constants in this package and the only one that worked was "Carbohydrates".

Also **thank you for this package**! I am not very familiar with iOS development, but if Carbohydrates work, I think I can try helping fix this problem, given it's a bug and not missconfiguration by me...

**Comment by Macelai** [comment]
Hey @fakeheal, probably you need to change these permissions on `getReadPermFromText` on `RCTAppleHealthKit+TypesAndPermissions.m`, would you like to open a PR for that?
