### ISSUE TITLE
TypeError: undefined is not a function (near '..._reactNativeHealth.default.initHealthKit...')

### ISSUE THREAD

**Issue by momotum** [agencyenterprise/react-native-health#86]
Hey guys,

installed the package and added the snippets.

import AppleHealthKit, { HealthKitPermissions } from "react-native-health";
...
AppleHealthKit.initHealthKit(permissions, (error: string) => {
...

TypeError: undefined is not a function (near '..._reactNativeHealth.default.initHealthKit...')

Cant get it running.

Interesting is that the AppleHealthKit doesn't even have the Method.

`Object {
  "Constants": Object {
    "Activities": Object {
      "AmericanFootball": "AmericanFootball",
      "Archery": "Archery",
      "AustralianFootball": "AustralianFootball",
      "Badminton": "Badminton",
      "Barre": "Barre",
      "Baseball": "Baseball",
      "Basketball": "Basketball",
      "Bowling": "Bowling",
      "Boxing": "Boxing",
      "CardioDance": "CardioDance",
      "Climbing": "Climbing",
      "Cooldown": "Cooldown",
      "CoreTraining": "CoreTraining",
      "Cricket": "Cricket",
      "CrossCountrySkiing": "CrossCountrySkiing",
      "CrossTraining": "CrossTraining",
      "Curling": "Curling",
      "Cycling": "Cycling",
      "Dance": "Dance",
      "DiscSports": "DiscSports",
      "DownhillSkiing": "DownhillSkiing",
      "Elliptical": "Elliptical",
      "EquestrianSports": "EquestrianSports",
      "Fencing": "Fencing",
      "Fishing": "Fishing",
      "FitnessGaming": "FitnessGaming",
      "Flexibility": "Flexibility",
      "FunctionalStrengthTraining": "FunctionalStrengthTraining",
      "Golf": "Golf",
      "Gymnastics": "Gymnastics",
      "HandCycling": "HandCycling",
      "Handball": "Handball",
      "HighIntensityIntervalTraining": "HighIntensityIntervalTraining",
      "Hiking": "Hiking",
      "Hockey": "Hockey",
      "Hunting": "Hunting",
      "JumpRope": "JumpRope",
      "Kickboxing": "Kickboxing",
      "Lacrosse": "Lacrosse",
      "MartialArts": "MartialArts",
      "MindAndBody": "MindAndBody",
      "MixedCardio": "MixedCardio",
      "PaddleSports": "PaddleSports",
      "Pickleball": "Pickleball",
      "Pilates": "Pilates",
      "Play": "Play",
      "PreparationAndRecovery": "PreparationAndRecovery",
      "Racquetball": "Racquetball",
      "Rowing": "Rowing",
      "Rugby": "Rugby",
      "Running": "Running",
      "Sailing": "Sailing",
      "SkatingSports": "SkatingSports",
      "SnowSports": "SnowSports",
      "Snowboarding": "Snowboarding",
      "Soccer": "Soccer",
      "SocialDance": "SocialDance",
      "Softball": "Softball",
      "Squash": "Squash",
      "StairClimbing": "StairClimbing",
      "Stairs": "Stairs",
      "StepTraining": "StepTraining",
      "SurfingSports": "SurfingSports",
      "Swimming": "Swimming",
      "TableTennis": "TableTennis",
      "TaiChi": "TaiChi",
      "Tennis": "Tennis",
      "TrackAndField": "TrackAndField",
      "TraditionalStrengthTraining": "TraditionalStrengthTraining",
      "Volleyball": "Volleyball",
      "Walking": "Walking",
      "WaterFitness": "WaterFitness",
      "WaterPolo": "WaterPolo",
      "WaterSports": "WaterSports",
      "WheelchairRunPace": "WheelchairRunPace",
      "WheelchairWalkPace": "WheelchairWalkPace",
      "Wrestling": "Wrestling",
      "Yoga": "Yoga",
    },
    "Observers": Object {
      "Cycling": "Cycling",
      "HeartRate": "HeartRate",
      "RestingHeartRate": "RestingHeartRate",
      "Running": "Running",
      "StairClimbing": "StairClimbing",
      "Walking": "Walking",
      "Workout": "Workout",
    },
    "Permissions": Object {
      "ActiveEnergyBurned": "ActiveEnergyBurned",
      "AppleExerciseTime": "AppleExerciseTime",
      "AppleStandTime": "AppleStandTime",
      "BasalEnergyBurned": "BasalEnergyBurned",
      "BiologicalSex": "BiologicalSex",
      "Biotin": "Biotin",
      "BloodAlcoholContent": "BloodAlcoholContent",
      "BloodGlucose": "BloodGlucose",
      "BloodPressureDiastolic": "BloodPressureDiastolic",
      "BloodPressureSystolic": "BloodPressureSystolic",
      "BloodType": "BloodType",
      "BodyFatPercentage": "BodyFatPercentage",
      "BodyMass": "BodyMass",
      "BodyMassIndex": "BodyMassIndex",
      "BodyTemperature": "BodyTemperature",
      "Caffeine": "Caffeine",
      "Calcium": "Calcium",
      "Carbohydrates": "Carbohydrates",
      "Chloride": "Chloride",
      "Cholesterol": "Cholesterol",
      "Copper": "Copper",
      "DateOfBirth": "DateOfBirth",
      "DistanceCycling": "DistanceCycling",
      "DistanceSwimming": "DistanceSwimming",
      "DistanceWalkingRunning": "DistanceWalkingRunning",
      "EnergyConsumed": "EnergyConsumed",
      "FatMonounsaturated": "FatMonounsaturated",
      "FatPolyunsaturated": "FatPolyunsaturated",
      "FatSaturated": "FatSaturated",
      "FatTotal": "FatTotal",
      "Fiber": "Fiber",
      "FlightsClimbed": "FlightsClimbed",
      "Folate": "Folate",
      "HeartRate": "HeartRate",
      "HeartRateVariability": "HeartRateVariability",
      "Height": "Height",
      "Iodine": "Iodine",
      "Iron": "Iron",
      "LeanBodyMass": "LeanBodyMass",
      "Magnesium": "Magnesium",
      "Manganese": "Manganese",
      "MindfulSession": "MindfulSession",
      "Molybdenum": "Molybdenum",
      "Niacin": "Niacin",
      "NikeFuel": "NikeFuel",
      "OxygenSaturation": "OxygenSaturation",
      "PantothenicAcid": "PantothenicAcid",
      "Phosphorus": "Phosphorus",
      "Potassium": "Potassium",
      "Protein": "Protein",
      "RespiratoryRate": "RespiratoryRate",
      "RestingHeartRate": "RestingHeartRate",
      "Riboflavin": "Riboflavin",
      "Selenium": "Selenium",
      "SleepAnalysis": "SleepAnalysis",
      "Sodium": "Sodium",
      "StepCount": "StepCount",
      "Steps": "Steps",
      "Sugar": "Sugar",
      "Thiamin": "Thiamin",
      "VitaminA": "VitaminA",
      "VitaminB12": "VitaminB12",
      "VitaminB6": "VitaminB6",
      "VitaminC": "VitaminC",
      "VitaminD": "VitaminD",
      "VitaminE": "VitaminE",
      "VitaminK": "VitaminK",
      "Vo2Max": "Vo2Max",
      "Water": "Water",
      "Weight": "Weight",
      "Workout": "Workout",
      "Zinc": "Zinc",
    },
    "Units": Object {
      "bpm": "bpm",
      "calorie": "calorie",
      "celsius": "celsius",
      "count": "count",
      "day": "day",
      "fahrenheit": "fahrenheit",
      "foot": "foot",
      "gram": "gram",
      "hour": "hour",
      "inch": "inch",
      "joule": "joule",
      "kilocalorie": "kilocalorie",
      "meter": "meter",
      "mgPerdL": "mgPerdL",
      "mile": "mile",
      "minute": "minute",
      "mlPerKgMin": "mlPerKgMin",
      "mmhg": "mmhg",
      "mmolPerL": "mmolPerL",
      "percent": "percent",
      "pound": "pound",
      "second": "second",
    },
  },
}`

I also added the info.plist.

It is just full of Enums.

Best regards Flo

**Comment by momotum** [comment]
solved

**Comment by TrishaGupta** [comment]
How did you solve this?

**Comment by Prakhar-64** [comment]
@momotum I'm still facing same issue. Please help me
