### ISSUE TITLE
Save workout doesn't allow me to add any parameters, like distance or energy burned

### ISSUE THREAD

**Issue by ronneldavis** [agencyenterprise/react-native-health#92]
**Describe the bug**
Save workout doesn't allow me to add any parameters, like distance or energy burned, as specified in the documentation. The type definition doesn't provide anything either. I am trying to save a cycling workout and I would like to save distance and power output.

**To Reproduce**
```typescript
let options: HealthActivityOptions = {
    type: "Cycling", // See HealthActivity Enum
    startDate: new Date(lastRide.start_at).toISOString(),
    endDate: new Date(lastRide.end_at).toISOString(),
    energyBurned: lastRide.calories, // In Energy burned unit
    distance: lastRide.distance * 1000, // In Distance unit
};

AppleHealthKit.saveWorkout(options,  (err, results) => {
    if (err) {
        console.log('error saving workout to Healthkit: ', err)
        return
    }]
    // workout successfully saved
})
```

**Expected behavior**
The distance and energyBurned are sent to HealthKit

**Screenshots**
![Simulator Screen Shot - iPhone 12 - 2021-04-24 at 14 05 33](https://user-images.githubusercontent.com/2377845/115955190-2db2a000-a506-11eb-95bf-098bc899f306.png)

**Smartphone (please complete the following information):**

- Device: iPhone 12
- OS: iOS 14.4
- Version 1.7.1

**Additional context**

**Comment by Macelai** [comment]
Hey @ronneldavis

Looks like it has some more steps to save the workout, from the apple documentation it says that should "calling the health store’s add(_:to:completion:) method.". See https://developer.apple.com/documentation/healthkit/hkworkout/1615739-init and https://developer.apple.com/documentation/healthkit/workouts_and_activity_rings/adding_samples_to_a_workout?language=objc

Feel free to open a PR for that!

**Comment by fakeheal** [comment]
@Macelai these methods are "optional" and shouldn't be used if you don't have actual samples (values at specific time) during the workouts that's being saved.

If you want to save total calories burned and total distance for the workout, you can do so with the current version of the package, by supplying `distanceUnit` and `energyBurnedUnit`, like this:

```
let options: HealthActivityOptions = {
  type: 'Cycling', // See HealthActivity Enum
  startDate: new Date(2021, 4, 17, 12, 0, 0).toISOString(),
  endDate: new Date(2021, 4, 17, 13, 30, 0).toISOString(),
  energyBurned: 150.00,
  energyBurnedUnit: 'calorie', // You can use `HealthUnit` constants
  distanceUnit: 'meter', // You can use `HealthUnit` constants
  distance: 3 * 1000,
}

AppleHealthKit.saveWorkout(options, (err, results) => {
  if (err) {
    console.log('error saving workout to Healthkit: ', err);
    return null;
  }
  console.log(results);
});
```

I have created a PR for updating the documentation.

**Comment by ronneldavis** [comment]
@fakeheal Thats exactly what I was looking for, thanks for that!

**Comment by Macelai** [comment]
Thanks for clarifying @fakeheal, amazing!

**Comment by liteupmedia** [comment]
This is not working anymore? Tried the same code and the workout shows up in my health but with no calories or distance.

> @macelai these methods are "optional" and shouldn't be used if you don't have actual samples (values at specific time) during the workout that's being saved.
> 
> If you want to save total calories burned and total distance for the workout, you can do so with the current version of the package, by supplying `distanceUnit` and `energyBurnedUnit`, like this:
> 
> ```
> let options: HealthActivityOptions = {
>   type: 'Cycling', // See HealthActivity Enum
>   startDate: new Date(2021, 4, 17, 12, 0, 0).toISOString(),
>   endDate: new Date(2021, 4, 17, 13, 30, 0).toISOString(),
>   energyBurned: 150.00,
>   energyBurnedUnit: 'calorie', // You can use `HealthUnit` constants
>   distanceUnit: 'meter', // You can use `HealthUnit` constants
>   distance: 3 * 1000,
> }
> 
> AppleHealthKit.saveWorkout(options, (err, results) => {
>   if (err) {
>     console.log('error saving workout to Healthkit: ', err);
>     return null;
>   }
>   console.log(results);
> });
> ```
> 
> Required parameters can be seen in the native method `workout_save`, here: [RCTAppleHealthKit+Methods_Workout.m](https://github.com/agencyenterprise/react-native-health/blob/master/RCTAppleHealthKit/RCTAppleHealthKit%2BMethods_Workout.m#L53)
> 
> I have created a PR for updating the documentation.

**Comment by phungmaiton** [comment]
> Hey [@ronneldavis](https://github.com/ronneldavis)
> 
> Looks like it has some more steps to save the workout, from the apple documentation it says that should "calling the health store’s `add(_:to:completion:)` method.". See
> 
> * https://developer.apple.com/documentation/healthkit/hkworkout/1615739-init
> * https://developer.apple.com/documentation/healthkit/workouts_and_activity_rings/adding_samples_to_a_workout?language=objc
> 
> Feel free to open a PR for that!

Do we have this available in the package yet?
