### ISSUE TITLE
Is there a way to remove permissions from inside the app or it can only be done in the settings page?

### ISSUE THREAD

**Issue by chefk5** [agencyenterprise/react-native-health#96]
I was able to turn on permissions from inside the app using a button. So for turning them off, is there a function for it or the user should turn them off via the settings page?

**Comment by lucaspbordignon** [comment]
Welcome, @chefk5! 👋🏾 

HealhKit doesn't have support for disabling permissions after they are requested

However, letting permissions enabled for HealthKit shouldn't influence your app, as the permissions check is done by the OS when requesting health samples

Could you give us more context, so we can give a more precise answer or alternative to your use-case 🙂

**Comment by chefk5** [comment]
Hello @lucaspbordignon !

I have a switch where when it is on, it asks for user permission to enable healthkit. But I think when it is turned off again, it seems that I have to do some validations inside the app while keeping permissions turned **on**  on the phone.
