### ISSUE TITLE
App crashes in iOS simulator if permissions are rejected.

### ISSUE THREAD

**Issue by j-carvalho** [agencyenterprise/react-native-health#97]
**Describe the bug**
When using the iOS simulator, during the permission process, if the permissions are not allowed, the app immediately crashes when using one of the methods, e.g. get steps.

The callback with the error string is not even executed and wrapping the method in a try/catch also brings no effect.

This works fine on an actual device.

**To Reproduce**

Using the iOS simulator.
1. Go to feature that opens healthkit permissions.
2. Click not allow
3. Query for steps

**Expected behavior**
The methods should work and not crash the app and return 0 values.

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fakeheal** [comment]
I tried reproducing your problem, by using the `example/` project in this repository, changed `App.tsx` ([see my changes](https://gist.github.com/fakeheal/efc2e5a4626aa7d2a99f22fd17e7da0e)) to request read and write permissions for steps, and then query them.

If I press the "Don't allow" button in the right top corner of the permissions screen, I get presented with an alert telling me how to enable the requested permissions later and in the console I have this:

``` {"endDate": "2021-05-17T13:39:55.042+0300", "startDate": "2021-05-17T13:39:55.042+0300", "value": 0}```

My simulator specs are as follows: iPhone 12 mini with iOS 14.5 ran using XCode 12.5 on Big Sur 11.3.1.

Can you please provide a repository with your code that crashes simulators when permissions are rejected?

**Comment by brianedelman** [comment]
This was happening for me too. My default simulator is on ios 13.7 and that's the only simulator where it crashes for me. Not sure if that's the issue totally though

**Comment by fyftech** [comment]
We're facing the same issue with iOS 13 simulators and devices. Any one come up with a workaround for now?

**Comment by brianedelman** [comment]
Any news here? This causes the app to become completely unusable in iso 13

**Comment by fyftech** [comment]
Hello, we are working on this right now.

Please allow us 7 working days time.

Regards
